/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SqlConverterIndexRouteImport } from './routes/sql-converter/index'
import { Route as PercentageCalculatorIndexRouteImport } from './routes/percentage-calculator/index'
import { Route as MeetingCostCalculatorIndexRouteImport } from './routes/meeting-cost-calculator/index'
import { Route as CurrencyConverterIndexRouteImport } from './routes/currency-converter/index'
import { Route as CreditSimulatorIndexRouteImport } from './routes/credit-simulator/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlConverterIndexRoute = SqlConverterIndexRouteImport.update({
  id: '/sql-converter/',
  path: '/sql-converter/',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageCalculatorIndexRoute =
  PercentageCalculatorIndexRouteImport.update({
    id: '/percentage-calculator/',
    path: '/percentage-calculator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeetingCostCalculatorIndexRoute =
  MeetingCostCalculatorIndexRouteImport.update({
    id: '/meeting-cost-calculator/',
    path: '/meeting-cost-calculator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurrencyConverterIndexRoute = CurrencyConverterIndexRouteImport.update({
  id: '/currency-converter/',
  path: '/currency-converter/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditSimulatorIndexRoute = CreditSimulatorIndexRouteImport.update({
  id: '/credit-simulator/',
  path: '/credit-simulator/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credit-simulator/': typeof CreditSimulatorIndexRoute
  '/currency-converter/': typeof CurrencyConverterIndexRoute
  '/meeting-cost-calculator/': typeof MeetingCostCalculatorIndexRoute
  '/percentage-calculator/': typeof PercentageCalculatorIndexRoute
  '/sql-converter/': typeof SqlConverterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credit-simulator': typeof CreditSimulatorIndexRoute
  '/currency-converter': typeof CurrencyConverterIndexRoute
  '/meeting-cost-calculator': typeof MeetingCostCalculatorIndexRoute
  '/percentage-calculator': typeof PercentageCalculatorIndexRoute
  '/sql-converter': typeof SqlConverterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credit-simulator/': typeof CreditSimulatorIndexRoute
  '/currency-converter/': typeof CurrencyConverterIndexRoute
  '/meeting-cost-calculator/': typeof MeetingCostCalculatorIndexRoute
  '/percentage-calculator/': typeof PercentageCalculatorIndexRoute
  '/sql-converter/': typeof SqlConverterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credit-simulator/'
    | '/currency-converter/'
    | '/meeting-cost-calculator/'
    | '/percentage-calculator/'
    | '/sql-converter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credit-simulator'
    | '/currency-converter'
    | '/meeting-cost-calculator'
    | '/percentage-calculator'
    | '/sql-converter'
  id:
    | '__root__'
    | '/'
    | '/credit-simulator/'
    | '/currency-converter/'
    | '/meeting-cost-calculator/'
    | '/percentage-calculator/'
    | '/sql-converter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditSimulatorIndexRoute: typeof CreditSimulatorIndexRoute
  CurrencyConverterIndexRoute: typeof CurrencyConverterIndexRoute
  MeetingCostCalculatorIndexRoute: typeof MeetingCostCalculatorIndexRoute
  PercentageCalculatorIndexRoute: typeof PercentageCalculatorIndexRoute
  SqlConverterIndexRoute: typeof SqlConverterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-converter/': {
      id: '/sql-converter/'
      path: '/sql-converter'
      fullPath: '/sql-converter/'
      preLoaderRoute: typeof SqlConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage-calculator/': {
      id: '/percentage-calculator/'
      path: '/percentage-calculator'
      fullPath: '/percentage-calculator/'
      preLoaderRoute: typeof PercentageCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-cost-calculator/': {
      id: '/meeting-cost-calculator/'
      path: '/meeting-cost-calculator'
      fullPath: '/meeting-cost-calculator/'
      preLoaderRoute: typeof MeetingCostCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-converter/': {
      id: '/currency-converter/'
      path: '/currency-converter'
      fullPath: '/currency-converter/'
      preLoaderRoute: typeof CurrencyConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-simulator/': {
      id: '/credit-simulator/'
      path: '/credit-simulator'
      fullPath: '/credit-simulator/'
      preLoaderRoute: typeof CreditSimulatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditSimulatorIndexRoute: CreditSimulatorIndexRoute,
  CurrencyConverterIndexRoute: CurrencyConverterIndexRoute,
  MeetingCostCalculatorIndexRoute: MeetingCostCalculatorIndexRoute,
  PercentageCalculatorIndexRoute: PercentageCalculatorIndexRoute,
  SqlConverterIndexRoute: SqlConverterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
